name: Python CI

on:
  push:
    branches:
      - main  # Change this to your default branch (e.g., master)
  pull_request:
    branches:
      - main  # Change this to your default branch (e.g., master)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run tests (make sure you have tests written)
      - name: Run tests with pytest
        run: |
          pytest

      # # Deploy to Streamlit Cloud (via GitHub integration)
      # - name: Deploy to Streamlit Cloud
      #   run: |
      #     curl -sSL https://get.streamlit.io | bash
      #     streamlit deploy --token {{ secrets.STREAMLIT_TOKEN }} --app-path app.py
